const preguntasPorEtapa = {
  'Infancia': [
    '¿Cuál es tu primer recuerdo feliz y por qué lo recuerdas con tanto cariño?',
    '¿Qué persona marcó tu infancia y qué aprendiste de ella?',
    '¿Cómo era un día perfecto para ti cuando eras niña/o?',
    '¿Qué olor, sonido o imagen te transporta directamente a tu niñez?',
    '¿Hay alguna historia familiar que te contaban y te hacía soñar?',
    '¿Cuál fue la travesura que más recuerdas?',
    '¿Qué te hacía sentir segura/o en tu infancia?',
    '¿Había algún objeto o juguete que fuera tu tesoro?',
    '¿Cómo viviste tu primer día de escuela?',
    '¿Qué aprendiste sobre el amor o la amistad siendo pequeña/o?',
    '¿Hubo alguna pérdida o tristeza en esa etapa que aún recuerdes?',
    '¿A quién admirabas profundamente en ese entonces?',
    '¿Qué te gustaba imaginar o soñar cuando estabas sola/o?',
    '¿Hay alguna foto de tu infancia que ames? ¿Qué historia hay detrás?',
    '¿Qué costumbre o tradición familiar te hacía sentir parte de algo más grande?',
  ],
  'Adolescencia': [
    '¿Cuándo sentiste por primera vez que estabas cambiando por dentro?',
    '¿Cuál fue tu mayor inseguridad y cómo la sobrellevaste?',
    '¿Hay una amistad de esa época que te marcó profundamente?',
    '¿Qué descubriste sobre ti misma/o en esos años turbulentos?',
    '¿Cómo te relacionabas con tu cuerpo y tu identidad?',
    '¿Quién fue tu confidente o tu refugio emocional?',
    '¿Te enamoraste por primera vez? ¿Cómo viviste esa experiencia?',
    '¿Cuál fue tu mayor acto de valentía en la adolescencia?',
    '¿Qué te daba miedo perder?',
    '¿Qué libro, película o canción te ayudó a entenderte mejor?',
    '¿Hay un secreto que guardabas entonces y hoy quisieras compartir?',
    '¿Qué injusticia viviste o presenciaste y cómo te afectó?',
    '¿Cómo era tu relación con tu familia?',
    '¿Qué te hacía sentir libre y viva/o?',
    '¿Qué sueño nacía dentro de ti y querías alcanzar a toda costa?',
  ],
  'Juventud': [
    '¿Qué decisiones tomaste que marcaron tu camino?',
    '¿Qué te impulsaba a seguir cuando todo parecía difícil?',
    '¿Qué lugar o ciudad te cambió para siempre?',
    '¿Cómo era tu vida cuando te sentías más independiente?',
    '¿Con quién compartiste momentos que hoy atesoras?',
    '¿Qué te dolió dejar atrás para crecer?',
    '¿Qué causa o idea te hizo luchar con pasión?',
    '¿Qué errores cometiste que luego te ayudaron a madurar?',
    '¿Hay una historia de amor que marcó tu juventud?',
    '¿Qué aprendizaje valioso llevas de esa etapa?',
    '¿Qué trabajo o experiencia fue tu primera prueba en la vida adulta?',
    '¿Cómo gestionabas tus emociones en esa etapa?',
    '¿Qué sueños tenías sobre el futuro?',
    '¿Qué te hubiera gustado saber entonces que hoy sabes?',
    '¿Cómo te veías a ti misma/o en el espejo de aquellos años?',
  ],
  'Adulto Joven': [
    '¿Cómo equilibraste tus responsabilidades con tus deseos personales?',
    '¿Qué metas te obsesionaban y por qué?',
    '¿Qué desafío profesional o personal te transformó?',
    '¿Quién fue tu mayor apoyo o inspiración en ese tiempo?',
    '¿Qué aprendiste sobre el amor propio?',
    '¿Qué decisiones tomaste pensando en otros más que en ti?',
    '¿Cómo era tu relación con el éxito y el fracaso?',
    '¿A qué renunciaste y qué obtuviste a cambio?',
    '¿Qué hábito o creencia tuviste que desaprender?',
    '¿Qué te hacía sentir que ibas en la dirección correcta?',
    '¿Quién te enseñó algo importante de forma inesperada?',
    '¿Hubo algún momento que sentiste que todo valía la pena?',
    '¿Qué fue lo más difícil de aceptar de ti misma/o?',
    '¿Cómo cambiaron tus vínculos en esa etapa?',
    '¿En qué momento dijiste “esto soy yo, sin disfraces”?',
  ],
  'Adulto Mayor': [
    '¿Qué aprendizajes sientes que solo el tiempo te ha dado?',
    '¿Cuál es tu mayor tesoro emocional hoy?',
    '¿Qué errores abrazas como parte de tu historia?',
    '¿Quiénes son tus personas faro, esas que iluminan tu camino?',
    '¿Qué significa para ti la palabra “sabiduría”?',
    '¿Qué cosas simples te llenan el alma cada día?',
    '¿Qué legado te gustaría dejar en este mundo?',
    '¿Qué palabras usarías para describir la paz?',
    '¿Hay algo que aprendiste tarde pero agradeces profundamente?',
    '¿Cómo ha cambiado tu forma de amar?',
    '¿Quién te inspira a seguir creciendo?',
    '¿Qué historia familiar sientes que debes transmitir?',
    '¿A qué renunciaste y hoy lo ves con calma?',
    '¿Cómo honras tu historia cada día?',
    '¿Qué te gustaría que el mundo supiera sobre ti antes de irte?',
  ],
  'Mensaje final': [
    '¿Qué palabras necesitas decir antes de cerrar tu historia?',
    '¿Cómo resumirías tu vida en una frase?',
    '¿Qué le dirías hoy a tu yo del pasado?',
    '¿Qué esperas que recuerden de ti cuando ya no estés?',
    '¿Qué te llena de gratitud al mirar hacia atrás?',
    '¿A quién te gustaría abrazar aunque sea una vez más?',
    '¿Qué símbolo representa tu vida?',
    '¿Qué te gustaría que lean tus nietos sobre ti?',
    '¿Qué carta dejarías escrita al mundo?',
    '¿Qué historia no quieres que muera contigo?',
    '¿Qué imagen guardas como final perfecto de tu película personal?',
    '¿Cómo quisieras ser recordada/o en un mural de memorias?',
    '¿Qué música, poema o palabra te representa hoy?',
    '¿Qué emoción te embarga cuando piensas en la palabra “vida”?',
    '¿Qué legado silencioso estás dejando sin darte cuenta?',
  ],
};

export default preguntasPorEtapa;
